# Configuração Jekyll para CONECTA Rural Telecom
title: "CONECTA Rural Telecom"
description: "Internet de alta velocidade para áreas rurais - Onde a fibra não chega, nós chegamos!"
url: "https://conectarural.com.br"
baseurl: ""

# SEO settings
author: "CONECTA Rural Telecom"
twitter:
  username: conectarural
  card: summary_large_image

# Social media
social:
  name: CONECTA Rural Telecom
  links:
    - https://facebook.com/conectarural
    - https://instagram.com/conectarural
    - https://linkedin.com/company/conectarural

# Google Analytics (substitua pelo seu ID)
google_analytics: G-XXXXXXXXXX

# Jekyll settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Collections (para futuras páginas)
collections:
  servicos:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "CONECTA Rural Team"

# Exclude from processing
exclude:
  - README.md
  - LICENSE
  - node_modules/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/

# Include files
include:
  - _pages

# Compression (para otimização)
sass:
  style: compressed

# Cache settings
incremental: true
